### Student Calendar Page APIs
### Shows selected timetables across courses and lesson schedules

@baseUrl = https://todu.mn/bs/lms/v1
@email = schoolstudent@must.edu.mn
@password = 123
@accessToken = p7vXn3LH7JGiL543jqmNTA

@userId = 539
@schoolId = 2
@courseId = 204
@lessonId = 228
@timetableId = 1


### 1. Login
# @name login
POST {{baseUrl}}/token/email
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "push_token": ""
}


### 2. Enrolled courses (used to iterate timetables)
GET {{baseUrl}}/users/{{userId}}/courses/enrolled
Authorization: Bearer {{accessToken}}


### 3. Get available timetable slots for a course
GET {{baseUrl}}/courses/{{courseId}}/timetables
Authorization: Bearer {{accessToken}}


### 4. Get my selected timetable rows for a course
GET {{baseUrl}}/courses/{{courseId}}/timetables/my
Authorization: Bearer {{accessToken}}


### 5. Select a timetable row
POST {{baseUrl}}/courses/{{courseId}}/timetables/my
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "timetable_id": {{timetableId}}
}


### 6. Cancel a selected timetable row
DELETE {{baseUrl}}/courses/{{courseId}}/timetables/my/{{timetableId}}
Authorization: Bearer {{accessToken}}


### 7. Get per-lesson concrete date/time schedule (attendance windows)
GET {{baseUrl}}/lessons/{{lessonId}}/timetables
Authorization: Bearer {{accessToken}}


### 8. Get course lessons (to place on calendar)
GET {{baseUrl}}/courses/{{courseId}}/lessons
Authorization: Bearer {{accessToken}}


### 9. Get my upcoming exams (exam events on calendar)
GET {{baseUrl}}/users/me/exams
Authorization: Bearer {{accessToken}}


### 10. Master data - lesson types (for legend/colors)
GET {{baseUrl}}/lesson-types
Authorization: Bearer {{accessToken}}
