@baseUrl = https://todu.mn/bs/lms/v1
@schoolId = 2
@userId = 539

@courseId = 204

@accessToken = YCJOeDHVGkNSymwXCEdjpA

@roleId = 10

### 1. user login
POST {{baseUrl}}/token/email
Content-Type: application/json

{
  "email": "schoolstudent@must.edu.mn",
  "password": "123",
  "push_token": "fcm_token_optional"
}


{
  "access_token": "YCJOeDHVGkNSymwXCEdjpA",
  "refresh_token": "c2Nob29sc3R1ZGVudGwwMDUxeHZjaGI2N25xZnphNjhhMjAyNjA0MDYwNzE1MTU=",
  "expires_in": 3600,
  "status": "success",
  "message": null
}

### Get own info
GET {{baseUrl}}/users/me
Authorization: Bearer {{accessToken}}

{
  "id": 539,
  "first_name": "Оюутан",
  "last_name": "-",
  "family_name": "-",
  "picture": "no-image.jpg",
  "username": "schoolstudent",
  "email": "schoolstudent@must.edu.mn",
  "phone": null,
  "facebook_id": null,
  "schools": [
    {
      "id": 2,
      "name": "Мэдээлэл, Холбооны Технологийн Сургууль",
      "role": {
        "id": 30,
        "name": "Суралцагч"
      }
    },
    {
      "id": 0,
      "name": "Humuun.edu.mn Нээлттэй орчин",
      "role": {
        "id": 30,
        "name": "Суралцагч"
      }
    }
  ],
  "links": [
    {
      "rel": "collection",
      "href": "https://todu.mn/bs/lms/v1/users/"
    }
  ]
}


### get roles
GET {{baseUrl}}/roles
Authorization: Bearer {{accessToken}}

{
  "items": [
    {
      "id": 10,
      "name": "Админ",
      "created_by": 1,
      "created_on": "2024-12-13T17:00:00Z",
      "updated_by": 1,
      "updated_on": "2024-12-13T17:00:00Z",
      "priority": 1
    },
    {
      "id": 20,
      "name": "Сургагч",
      "created_by": 1,
      "created_on": "2024-12-13T17:00:00Z",
      "updated_by": 0,
      "updated_on": "2026-03-21T18:01:58.105509Z",
      "priority": 2
    },
    {
      "id": 30,
      "name": "Суралцагч",
      "created_by": 1,
      "created_on": "2024-12-13T17:00:00Z",
      "updated_by": 0,
      "updated_on": "2026-03-21T18:01:58.262689Z",
      "priority": 3
    }
  ],
  "hasMore": false,
  "limit": 25,
  "offset": 0,
  "count": 3,
  "links": [
    {
      "rel": "self",
      "href": "https://todu.mn/bs/lms/v1/roles"
    },
    {
      "rel": "edit",
      "href": "https://todu.mn/bs/lms/v1/roles"
    },
    {
      "rel": "describedby",
      "href": "https://todu.mn/bs/lms/metadata-catalog/v1/item"
    },
    {
      "rel": "first",
      "href": "https://todu.mn/bs/lms/v1/roles"
    }
  ]
}




### 3. Get role by ID
# GET /roles/{role_id}
# Headers: Authorization: Bearer <access_token>
GET {{baseUrl}}/roles/{{roleId}}
Authorization: Bearer {{accessToken}}


{
  "id": 10,
  "name": "Админ",
  "created_by": 1,
  "created_on": "2024-12-13T17:00:00Z",
  "updated_by": 1,
  "updated_on": "2024-12-13T17:00:00Z",
  "priority": 1,
  "links": [
    {
      "rel": "collection",
      "href": "https://todu.mn/bs/lms/v1/roles/"
    }
  ]
}